server:
  port: 8085

zuul:
  routes:
    account:
      path: /account/**
      url: http://localhost:8081/account
    auth:
      path: /auth/**
      url: http://localhost:8082/auth
    notification:
      path: /notification/**
      url: http://localhost:8083/notification
    registration:
      path: /registration/**
      url: http://localhost:8084/registration